name: C++

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  native:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2025
            cmake-args:
          - name: Windows aarch64
            os: windows-11-arm
            cmake-args:
          - name: Linux x86_64
            os: ubuntu-24.04
            cmake-args:
          - name: Linux aarch64
            os: ubuntu-24.04-arm
            cmake-args:
          - name: macOS universal
            os: macos-15
            cmake-args:

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Make GCC 14 the default toolchain (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 200
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 200

      - run: cmake -B build -S . -DBUILD_EXAMPLES=ON ${{ matrix.cmake-args }}
      - run: cmake --build build --config RelWithDebInfo --parallel 4
      - run: ctest --test-dir build -C RelWithDebInfo --output-on-failure
        if: ${{ !(matrix.skip-tests || false) }}
      - run: cmake --install build --config RelWithDebInfo --prefix pkg

      - uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.name }}
          path: pkg

  coverage:
    timeout-minutes: 20
    name: "Coverage"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Install LLVM 21
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21 all
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-21 200
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-21 200
          sudo update-alternatives --install /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-21 200
          sudo update-alternatives --install /usr/bin/llvm-profdata llvm-profdata /usr/bin/llvm-profdata-21 200
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV

      - run: ./tools/coverage-generate.sh template_test

      - uses: actions/upload-artifact@v5
        with:
          name: Coverage report
          path: ./build-coverage/coverage-line-by-line-template_test.html

      - name: Write to job summary
        run: |
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          cat ./build-coverage/coverage-report-template_test.txt >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
